version: '3.8'

services:
  pg:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=imagefeed_api
    ports:
      - 5432:5432
    networks:
      - imagefeed_api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: imagefeed_api
      SERVICE_PORT_REST: 3333
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_NAME: imagefeed_api
      POSTGRES_MAX_OPEN_CONNS: 50
      POSTGRES_MAX_CONN_LIFETIME: 10
      POSTGRES_MAX_IDLE_LIFETIME: 5
      FILE_STORAGE_BASE_URL: http://localhost:3333/
      FILE_STORAGE_BASE_PATH: storage/images/
    ports:
      - 3333:3333
    networks:
      - imagefeed_api
    depends_on:
      - pg

volumes:
  storage:

networks:
  imagefeed_api: